Adding test scripts

diff --git a/.test/run b/.test/run
--- a/.test/run
+++ b/.test/run
@@ -12,11 +12,18 @@ do
 done
 
 echo "--- Running test.py ---"
-if ! python test.py
+if ! python test.py >/dev/null
 then
   echo "Running test.py failed"
   exit -2
 fi
-echo "-----------------------"
 
-
+echo "--- Running Tests ---"
+for i in $(ls .test/test*.py)
+do
+	if ! python $i
+	then
+		echo "Test '$i' failed"
+		exit -3
+	fi
+done
